// Banco de Dados Oficial - Portfólio Vetter Empreendimentos
// Baseado na tabela oficial de 22/09/2026

export const DEVELOPMENTS_DATA = [
  {
    id: "south_beach",
    name: "South Beach",
    city: "Balneário Piçarras",
    address: "R. Tatuíra, 185 - Piçarras",
    status: "pronto", // "pronto" ou "obras"
    statusLabel: "Pronto para Morar",
    deliveryLabel: "Pronto (Chaves na mão)",
    deliveryDate: null, // Já entregue
    availableUnits: "1 unid. (Unid. 1002 - vazia)",
    limitFlow: "36x (IPCA + 1% a.m.)",
    distanceSea: "100 m",
    floors: 19,
    leisureArea: "1.000 m² (20 opções de lazer)",
    defaultUnitPrice: 2150000.00,
    defaultEntryPct: 20.0,
    defaultMonthlyPct: 80.0,
    defaultMonthlyCount: 36,
    defaultBoostPct: 0.0,
    defaultBoostCount: 0,
    defaultKeysPct: 0.0, // Chaves imediatas / fluxo direto
    highlights: ["Chaves na Mão", "100m da Praia", "19 Pavimentos", "20 Opções de Lazer"]
  },
  {
    id: "coral_gables",
    name: "Coral Gables",
    city: "Penha",
    address: "Av. Antônio J. Tavares, 838 - Penha",
    status: "pronto",
    statusLabel: "Pronto para Morar",
    deliveryLabel: "Pronto (Chaves na mão)",
    deliveryDate: null,
    availableUnits: "1 unid. (Unid. 3101 - vazia)",
    limitFlow: "36x (IPCA + 1% a.m.)",
    distanceSea: "120 m",
    floors: 32,
    leisureArea: "2.000 m² (20 opções de lazer)",
    defaultUnitPrice: 2480000.00,
    defaultEntryPct: 20.0,
    defaultMonthlyPct: 80.0,
    defaultMonthlyCount: 36,
    defaultBoostPct: 0.0,
    defaultBoostCount: 0,
    defaultKeysPct: 0.0,
    highlights: ["Chaves na Mão", "Torre Ícone com 32 Pavimentos", "120m do Mar", "2.000 m² Lazer"]
  },
  {
    id: "ocean_park",
    name: "Ocean Park",
    city: "Balneário Piçarras",
    address: "Av. Nereu Ramos, 3477 - Piçarras",
    status: "obras",
    statusLabel: "Em Obras - Fase Final",
    deliveryLabel: "Out/2026",
    deliveryDate: "2026-10",
    availableUnits: "5 unidades disponíveis",
    limitFlow: "20/80 (20% até chaves / 80% saldo)",
    distanceSea: "120 m",
    floors: 25,
    leisureArea: "3.000 m² (43 opções de lazer)",
    defaultUnitPrice: 1890000.00,
    defaultEntryPct: 10.0,
    defaultMonthlyPct: 10.0,
    defaultMonthlyCount: 1, // recalculado dinamicamente
    defaultBoostPct: 0.0,
    defaultBoostCount: 0,
    defaultKeysPct: 80.0,
    highlights: ["Mega Lazer 3.000 m²", "43 Opções de Lazer", "120m do Mar", "25 Pavimentos"]
  },
  {
    id: "gold_coast",
    name: "Gold Coast",
    city: "Balneário Piçarras",
    address: "Av. Nereu Ramos, 3654 - Piçarras",
    status: "obras",
    statusLabel: "Em Obras",
    deliveryLabel: "Ago/2027",
    deliveryDate: "2027-08",
    availableUnits: "5 unidades disponíveis",
    limitFlow: "30/70 (30% até chaves / 70% saldo)",
    distanceSea: "100 m",
    floors: 14,
    leisureArea: "2.100 m² (33 opções de lazer)",
    defaultUnitPrice: 1780000.00,
    defaultEntryPct: 10.0,
    defaultMonthlyPct: 20.0,
    defaultMonthlyCount: 10,
    defaultBoostPct: 0.0,
    defaultBoostCount: 0,
    defaultKeysPct: 70.0,
    highlights: ["Exclusividade 14 Pavimentos", "100m da Praia", "2.100 m² Lazer", "33 Opções"]
  },
  {
    id: "paradise_bay",
    name: "Paradise Bay",
    city: "Balneário Piçarras",
    address: "Av. Nereu Ramos, 3493 - Piçarras",
    status: "obras",
    statusLabel: "Em Obras",
    deliveryLabel: "Ago/2028",
    deliveryDate: "2028-08",
    availableUnits: "5 unidades disponíveis",
    limitFlow: "40/60 (40% até chaves / 60% saldo)",
    distanceSea: "120 m",
    floors: 25,
    leisureArea: "2.000 m² (28 opções de lazer)",
    defaultUnitPrice: 1950000.00,
    defaultEntryPct: 10.0,
    defaultMonthlyPct: 20.0,
    defaultMonthlyCount: 22,
    defaultBoostPct: 10.0,
    defaultBoostCount: 2,
    defaultKeysPct: 60.0,
    highlights: ["120m do Mar", "25 Pavimentos", "2.000 m² Lazer", "28 Opções"]
  },
  {
    id: "dolphin_bay",
    name: "Dolphin Bay",
    city: "Penha (Armação)",
    address: "Av. Itapocorói - Armação, Penha",
    status: "obras",
    statusLabel: "Em Obras",
    deliveryLabel: "Out/2028",
    deliveryDate: "2028-10",
    availableUnits: "2 unidades disponíveis",
    limitFlow: "40/60 (40% até chaves / 60% saldo)",
    distanceSea: "100 m",
    floors: 16,
    leisureArea: "700 m² (26 opções de lazer)",
    defaultUnitPrice: 1690000.00,
    defaultEntryPct: 10.0,
    defaultMonthlyPct: 20.0,
    defaultMonthlyCount: 24,
    defaultBoostPct: 10.0,
    defaultBoostCount: 2,
    defaultKeysPct: 60.0,
    highlights: ["Armação - Penha", "100m do Mar", "16 Pavimentos", "26 Opções de Lazer"]
  },
  {
    id: "emerald_coast",
    name: "Emerald Coast",
    city: "Balneário Piçarras",
    address: "Av. Nereu Ramos, 5955 - Piçarras",
    status: "obras",
    statusLabel: "Em Obras",
    deliveryLabel: "Mar/2029",
    deliveryDate: "2029-03",
    availableUnits: "15 unidades disponíveis",
    limitFlow: "40/60 (40% até chaves / 60% saldo)",
    distanceSea: "70 m",
    floors: 25,
    leisureArea: "1.400 m² (29 opções de lazer)",
    defaultUnitPrice: 1850000.00,
    defaultEntryPct: 10.0,
    defaultMonthlyPct: 20.0,
    defaultMonthlyCount: 29,
    defaultBoostPct: 10.0,
    defaultBoostCount: 2,
    defaultKeysPct: 60.0,
    highlights: ["Apenas 70m da Praia", "25 Pavimentos", "1.400 m² Lazer", "29 Opções"]
  },
  {
    id: "tropical_beach",
    name: "Tropical Beach",
    city: "Balneário Piçarras",
    address: "Av. Nereu Ramos - Piçarras",
    status: "obras",
    statusLabel: "Em Obras",
    deliveryLabel: "Jun/2029",
    deliveryDate: "2029-06",
    availableUnits: "7 unidades disponíveis",
    limitFlow: "40/60 (40% até chaves / 60% saldo)",
    distanceSea: "200 m",
    floors: 25,
    leisureArea: "1.500 m² (26 opções de lazer)",
    defaultUnitPrice: 1920000.00,
    defaultEntryPct: 10.0,
    defaultMonthlyPct: 20.0,
    defaultMonthlyCount: 32,
    defaultBoostPct: 10.0,
    defaultBoostCount: 3,
    defaultKeysPct: 60.0,
    highlights: ["200m da Praia", "25 Pavimentos", "1.500 m² Lazer", "26 Opções"]
  },
  {
    id: "royal_bay",
    name: "Royal Bay",
    city: "Penha (Armação)",
    address: "Av. Itapocorói, 1474 - Armação, Penha",
    status: "obras",
    statusLabel: "Em Obras - Torre Alta",
    deliveryLabel: "Out/2029",
    deliveryDate: "2029-10",
    availableUnits: "7 unidades disponíveis",
    limitFlow: "40/60 (40% até chaves / 60% saldo)",
    distanceSea: "80 m",
    floors: 40,
    leisureArea: "2.300 m² (29 opções de lazer)",
    defaultUnitPrice: 2280000.00,
    defaultEntryPct: 10.0,
    defaultMonthlyPct: 20.0,
    defaultMonthlyCount: 36,
    defaultBoostPct: 10.0,
    defaultBoostCount: 3,
    defaultKeysPct: 60.0,
    highlights: ["Torre Imponente 40 Pavimentos", "80m do Mar", "2.300 m² Lazer", "29 Opções"]
  },
  {
    id: "bal_harbour",
    name: "Bal Harbour",
    city: "Balneário Piçarras",
    address: "Av. Nereu Ramos - Piçarras",
    status: "obras",
    statusLabel: "Em Obras",
    deliveryLabel: "Mai/2030",
    deliveryDate: "2030-05",
    availableUnits: "30 unidades disponíveis",
    limitFlow: "40/60 (40% até chaves / 60% saldo)",
    distanceSea: "80 m",
    floors: 25,
    leisureArea: "1.400 m² (31 opções de lazer)",
    defaultUnitPrice: 2093725.72,
    defaultEntryPct: 11.94,
    defaultMonthlyPct: 45.0,
    defaultMonthlyCount: 44,
    defaultBoostPct: 20.0,
    defaultBoostCount: 4,
    defaultKeysPct: 23.06,
    highlights: ["80m da Praia de Piçarras", "25 Pavimentos", "1.400 m² Lazer", "31 Opções"]
  },
  {
    id: "fort_myers",
    name: "Fort Myers",
    city: "Penha (Armação)",
    address: "Av. Itapocorói, 1586 - Armação, Penha",
    status: "obras",
    statusLabel: "Em Obras - Maior Torre de Penha",
    deliveryLabel: "Set/2031",
    deliveryDate: "2031-09",
    availableUnits: "44 unidades disponíveis",
    limitFlow: "60/40 (60% até chaves / 40% saldo)",
    distanceSea: "67 m",
    floors: 46,
    leisureArea: "2.400 m² (29 opções de lazer)",
    defaultUnitPrice: 2390000.00,
    defaultEntryPct: 15.0,
    defaultMonthlyPct: 30.0,
    defaultMonthlyCount: 59,
    defaultBoostPct: 15.0,
    defaultBoostCount: 5,
    defaultKeysPct: 40.0,
    highlights: ["Maior Torre da Região: 46 Pavimentos", "Apenas 67m do Mar", "2.400 m² Lazer", "44 Unidades"]
  },
  {
    id: "custom",
    name: "Personalizado / Outro",
    city: "Litoral SC",
    address: "Empreendimento Sob Consulta",
    status: "obras",
    statusLabel: "Configuração Livre",
    deliveryLabel: "Definir na Proposta",
    deliveryDate: "2029-12",
    availableUnits: "Sob consulta",
    limitFlow: "Fluxo Sob Medida",
    distanceSea: "Sob consulta",
    floors: 0,
    leisureArea: "Área de lazer completa",
    defaultUnitPrice: 2000000.00,
    defaultEntryPct: 15.0,
    defaultMonthlyPct: 40.0,
    defaultMonthlyCount: 36,
    defaultBoostPct: 15.0,
    defaultBoostCount: 3,
    defaultKeysPct: 30.0,
    highlights: ["Fluxo Personalizado", "Flexibilidade Total", "Condições Especiais"]
  }
];
